### ISSUE TITLE
update nix dependency

### ISSUE THREAD

**Issue by Beiri22** [ranweiler/pete#10]
Since nix is in 0.x, the ^-specifier does not allow the update from 0.17 to 0.19

**Comment by ranweiler** [comment]
Hi @Beiri22, good idea, though I'm going to implement these changes individually. For a pre-1.0 package like `nix`, we should probably always track the latest release. I'll look into automating notifications about that.

**Comment by Beiri22** [comment]
Ok, seems reasonable.

**Comment by ranweiler** [comment]
@Beiri22, was there anything in the proposed `libc` update that was blocking you? I'll get to that update too (see #17), but I'm going to address the `Command` issue first, if not.

**Comment by Beiri22** [comment]
No, that did not cause trouble. I just checked the other versions, too.
