### ISSUE TITLE
Sometimes problems when tracing

### ISSUE THREAD

**Issue by Beiri22** [ranweiler/pete#28]
I am tracing a bash script that forks some sub-processes, maybe some sub-sub-processes, too.

In some cases the tracing runs without any problems, other times I get some error, like:
ESRCH: No such process on accessing the registers

```rust
while let Some(tracee) = self.tracer.wait()?
{
   let regs = tracee.registers()?;
   ...
}
```

I thought that the tracee should be in a stopped state in that situation. So how can it die in the meantime?

**Comment by ranweiler** [comment]
Sorry @Beiri22, I apparently wasn't getting email notifications for new issues!

First, per the [manual](https://man7.org/linux/man-pages/man2/ptrace.2.html):

> The tracer cannot assume that the ptrace-stopped tracee exists. [...] Therefore, the tracer must be prepared to handle an ESRCH error on any ptrace operation.

Check out the section "Death under ptrace".

That said, if you can provide a small script to repro behavior that seems wrong or broken, even given the above, I'm happy to dig in. If you do so, please do include version details for bash, Linux, &c.

**Comment by Beiri22** [comment]
No problem.

I have read the manpage now and try to work around it. As it happens randomly, it'll take some time to find the best way around. 

```rust
while let Some(tracee) = self.tracer.wait()?
{
  ...
  self.tracer.restart(tracee, Restart::Syscall)?; // WHEN ERROR OCCURRS HERE
  // what will happen, when I just ignore the error? Will the next tracer.wait() return Ok(None) or Err(...) 
}
```

**Comment by ranweiler** [comment]
> // what will happen, when I just ignore the error?

If the tracer has no more unwaited-on children, then the next call to `wait()` should return `Ok(None)`. We check for this in the implementation of `Ptracer::wait()`. In your above code snippet, if you ignored any errors on the attempted `restart()`, then the loop's condition/match `let Some(tracee) = self.tracer.wait()` would be refuted, and we would exit the loop.

I opened #29 to capture ideas for maybe failing faster when tracing is uninitialized, and making sure we handle `attach()` in the same way.

**Comment by Beiri22** [comment]
It's good, that the loop exits gracefully. I managed to ignore the error in restart and getRegisters, after checking that those occured only during exit phase of processes. As far as my first tests suggest, this solution seams reasonable.

**Comment by ranweiler** [comment]
@Beiri22, if you have a small shell script and test tracer you can share to repro the problem, I'll take a look at it and double-check that there's no underlying bug in `pete` that I can fix. Otherwise, can we close this issue?

**Comment by Beiri22** [comment]
I think you can close this issue, it looks good now. If I'll experience futher problems, I'll let you know.
