### ISSUE TITLE
Trouble tracing children through vfork

### ISSUE THREAD

**Issue by travitch** [ranweiler/pete#7]
I was playing around with this and ran into some panics at line 421 of ptracer.rs. I think the cause might be a missing call to `set_tracee_state` around https://github.com/ranweiler/pete/blob/master/src/ptracer.rs#L346. It seems to work with that. If you think that sounds reasonable, I can put together a PR.

**Comment by ranweiler** [comment]
Yep, I think you're right. A PR would be great!
